.front-react-common:
  rules:
    - changes:
        - 'front-react/*'

front_react_build:
  extends: .front-react-common
  stage: build
  script:
    - echo "Building react"
    - docker build 
      -f ./front-react/Dockerfile
      --build-arg API_URL="http://backend.local.dev" 
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from "$FRONT_REACT_DOCKER_BUILDER_IMAGE"
      --target builder
      -t $FRONT_REACT_DOCKER_BUILDER_IMAGE:$CI_COMMIT_SHORT_SHA ./front-react
    - docker tag $FRONT_REACT_DOCKER_BUILDER_IMAGE:$CI_COMMIT_SHORT_SHA  $FRONT_REACT_DOCKER_BUILDER_IMAGE:latest
    - docker push $FRONT_REACT_DOCKER_BUILDER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $FRONT_REACT_DOCKER_BUILDER_IMAGE:latest

front-react-test:
  extends: .front-react-common
  stage: test
  script:
    - echo "Testing react"
    - docker run $FRONT_REACT_DOCKER_BUILDER_IMAGE:latest sh -c "CI=true yarn test"
    - echo "Test successfully!"

front_react_deploy:
  extends: .front-react-common
  stage: deploy
  needs: ["front_react_build"]
  script:
    - echo "Deploying react"
    - docker build 
      -f ./front-react/Dockerfile
      --build-arg BUILDKIT_INLINE_CACHE=1
      --target deploy
      -t $FRONT_REACT_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA ./front-react
    - docker tag $FRONT_REACT_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA  $FRONT_REACT_DOCKER_IMAGE:latest
#    - docker push $FRONT_REACT_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $FRONT_REACT_DOCKER_IMAGE:latest
