.front-svelte-common:
  rules:
    - changes:
        - 'front-svelte/*'

front-svelte-build:
  extends: .front-svelte-common
  stage: build
  script:
    - echo "Building svelte"
    - docker build 
      -f ./front-react/Dockerfile
      --build-arg API_URL="http://backend.local.dev" 
      --build-arg BUILDKIT_INLINE_CACHE=1
      --cache-from "$FRONT_SVELTE_DOCKER_BUILDER_IMAGE"
      --target builder
      -t $FRONT_SVELTE_DOCKER_BUILDER_IMAGE:$CI_COMMIT_SHORT_SHA ./front-react
    - docker tag $FRONT_SVELTE_DOCKER_BUILDER_IMAGE:$CI_COMMIT_SHORT_SHA  $FRONT_SVELTE_DOCKER_BUILDER_IMAGE:latest
    - docker push $FRONT_SVELTE_DOCKER_BUILDER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $FRONT_SVELTE_DOCKER_BUILDER_IMAGE:latest

front-svelte-test:
  extends: .front-svelte-common
  stage: test
  script:
    - echo "Testing svelte"
    - docker run $FRONT_SVELTE_DOCKER_BUILDER_IMAGE:latest sh -c "CI=true yarn test"
    - echo "Test successfully!"

front-svelte-deploy:
  extends: .front-svelte-common
  stage: deploy
  needs: ["front-svelte-build"]
  script:
    - echo "Deploying svelte"
    - docker build 
      -f ./front-svelte/Dockerfile
      --build-arg BUILDKIT_INLINE_CACHE=1
      --target deploy
      -t $FRONT_SVELTE_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA ./front-svelte
    - docker tag $FRONT_SVELTE_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA  $FRONT_SVELTE_DOCKER_IMAGE:latest
#    - docker push $FRONT_SVELTE_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $FRONT_SVELTE_DOCKER_IMAGE:latest
