image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2

  FRONT_REACT_DOCKER_BUILDER_IMAGE: $CI_REGISTRY_IMAGE/front_react_build
  FRONT_REACT_DOCKER_IMAGE: $CI_REGISTRY_IMAGE/front_react

  FRONT_ANGULAR_DOCKER_BUILDER_IMAGE: $CI_REGISTRY_IMAGE/front_svelte_build
  $FRONT_ANGULAR_DOCKER_IMAGE: $CI_REGISTRY_IMAGE/front_svelte

  FRONT_SVELTE_DOCKER_BUILDER_IMAGE: $CI_REGISTRY_IMAGE/front_angular_build
  FRONT_SVELTE_DOCKER_IMAGE: $CI_REGISTRY_IMAGE/front_angular

  BACKEND_DOCKER_IMAGE: $CI_REGISTRY_IMAGE/backend

stages:
  - build # сборка
  - test # тестирование
  - deploy # развертывание

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

top-level-job:
  stage: build
  script:
    - echo "Hello world..."

include:
  - "front-react/.gitlab-ci.yml"
  - "front-angular/.gitlab-ci.yml"
  - "front-svelte/.gitlab-ci.yml"
  - "backend/.gitlab-ci.yml"
