.backend-common:
  rules:
    - changes:
        - 'backend/*'

backend-build:
  extends: .backend-common
  stage: build
  script:
    - echo "Building backend"

backend-deploy:
  extends: .backend-common
  stage: deploy
  script:
    - echo "Deploying backend"
    - docker build
      -f ./backend/Dockerfile
      -t BACKEND_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA ./backend
    - docker tag BACKEND_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA  BACKEND_DOCKER_IMAGE:latest
    - docker push BACKEND_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push BACKEND_DOCKER_IMAGE:latest