# Default values for kp-stand-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {
    kubernetes.io/ingress.class: nginx
  }

  hosts:
    - host: front-react.local.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: kp-stand-front-react
              port:
                number: 80
    - host: front-svelte.local.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: kp-stand-front-svelte
              port:
                number: 80
    - host: backend.local.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
              name: kp-stand-backend
              port:
                number: 80

  tls: []

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
