kind: Deployment
apiVersion: apps/v1
metadata:
  name: kp-stand-front-angular
  namespace: kp-stand
  labels:
    k8s-app: kp-stand-front-angular
    project: kp-stand
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: kp-stand-front-angular
  template:
    metadata:
      name: kp-stand-front-angular
      labels:
        k8s-app: kp-stand-front-angular
    spec:
      containers:
        - name: kp-stand-front-angular
          # docker image path
          image: localhost:5000/front_angular:latest
          imagePullPolicy: Never
---
kind: Service
apiVersion: v1
metadata:
  name: kp-stand-front-angular
  namespace: kp-stand
  labels:
    k8s-app: kp-stand-front-angular
    project: kp-stand
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    k8s-app: kp-stand-front-angular
